service: aqts-capture-load-test

provider:
  name: aws
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'TEST'}
  runtime: python3.8
  memorySize: 128
  timeout: 45
  logRetentionInDays: 90
  deploymentBucket:
    name: iow-cloud-applications
  stackTags:
    "wma:applicationId": "Aquarius TS Capture Load Test"
    "wma:contact": "Kenneth Kehl kkehl@contractor.usgs.gov"
    "wma:environment": ${self:provider.stage}
    "wma:taggingVersion": 0.0.1
    "wma:costCenter": TBD
    commitIdentifier: ${git:sha1}

custom:
  exportGitVariables: false
  accountNumber: ${ssm:/iow/aws/accountNumber}
  vpc:
    securityGroupIds: ${ssm:/iow/retriever-capture/${self:provider.stage}/securityGroupIds~split}
    subnetIds: ${ssm:/iow/aws/vpc/${self:provider.stage}/subnetIds~split}

functions:
  RestoreDbCluster:
    handler: src.handler.restore_db_cluster
    role: arn:aws:iam::${self:custom.accountNumber}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      MAX_RETRIES: 6
    vpc: ${self:custom.vpc}

  DeleteDbCluster:
    handler: src.handler.delete_db_cluster
    role: arn:aws:iam::${self:custom.accountNumber}:role/csr-Lambda-Role
    environment:
      AWS_DEPLOYMENT_REGION: ${self:provider.region}
      MAX_RETRIES: 6
    vpc: ${self:custom.vpc}

stepFunctions:
  stateMachines:
    aqtsLoadTest:
      type: EXPRESS
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - arn:aws:logs:${self:provider.region}:${self:custom.accountNumber}:log-group:step-functions-test:*
      role: arn:aws:iam::${self:custom.accountNumber}:role/step-functions-service-access
      name: aqts-capture-load-test-${self:provider.stage}
      definition:
        Comment: "AQTS Load Test"
        StartAt: RestoreDbCluster
        role: arn:aws:iam::${self:custom.accountNumber}:role/step-functions-service-access
        States:
          RestoreDbCluster:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-restoreDbCluster"
            Next: DeleteDbCluster
          DeleteDbCluster:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-deleteDbCluster"
            End: true

plugins:
  - serverless-plugin-git-variables
  - serverless-step-functions
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - Dockerfile
    - .dockerignore
    - Jenkinsfile
    - package.json
    - package-lock.json
